---
apiVersion: "v1"
data:
  # Password for Spacebears
  spacebears-password: {{if ne (typeOf .Values.secrets.SPACEBEARS_PASSWORD) "<nil>"}}{{if has (kindOf .Values.secrets.SPACEBEARS_PASSWORD) (list "map" "slice")}}{{.Values.secrets.SPACEBEARS_PASSWORD | toJson | b64enc | quote}}{{else}}{{.Values.secrets.SPACEBEARS_PASSWORD | b64enc | quote}}{{end}}{{else}}{{fail "secrets.SPACEBEARS_PASSWORD has not been set"}}{{end}}
kind: "Secret"
metadata:
  name: "secrets"
  labels:
    skiff-role-name: "secrets"
