---
# The secret-generation role contains the following jobs:
#
# - generate-uaa-secrets: This job will generate the secrets for the cluster
apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: "secret-generation"
spec:
  template:
    metadata:
      name: "secret-generation"
      labels:
        skiff-role-name: "secret-generation"
    spec:
      containers:
      - env:
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SECRETS_GENERATION_COUNTER"
          value: "1"
        - name: "KUBE_SECRETS_GENERATION_NAME"
          value: "secrets-1"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        image: "splatform/uaa-secret-generation:197cee7081a4980d51bf02a5250a1eabe3c9a65a"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "secret-generation"
        ports: ~
        readinessProbe: ~
        resources:
          requests:
            memory: "256Mi"
            cpu: "1000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "OnFailure"
      serviceAccountName: "secret-generator"
      terminationGracePeriodSeconds: 600
      volumes: ~
