---
# The acceptance-tests role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - acceptance-tests: The acceptance tests errand can be configured to run full
#   acceptance test suite against a specific Cloud Foundry API endpoint.
#   Consider running smoke tests errand for a smaller set of tests.
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "acceptance-tests"
  labels:
    skiff-role-name: "acceptance-tests"
spec:
  containers:
  - env:
    - name: "CLUSTER_ADMIN_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "cluster-admin-password"
          name: "secrets"
    - name: "DOMAIN"
      value: "cf-dev.io"
    - name: "INTERNAL_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert"
          name: "secrets"
    - name: "INTERNAL_CA_KEY"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-key"
          name: "secrets"
    - name: "KUBERNETES_NAMESPACE"
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: "MONIT_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "monit-password"
          name: "secrets"
    - name: "SCF_LOG_PROTOCOL"
      value: "tcp"
    - name: "UAA_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "uaa-ca-cert"
          name: "secrets"
    image: "splatform/scf-acceptance-tests:f48782350ed1f8aea5629cc9a8d4d35defe80604"
    lifecycle:
      preStop:
        exec:
          command:
          - "/opt/fissile/pre-stop.sh"
    livenessProbe: ~
    name: "acceptance-tests"
    ports: ~
    readinessProbe: ~
    resources:
      requests:
        memory: "876Mi"
        cpu: "2000m"
      limits: {}
    securityContext: ~
    volumeMounts: ~
  dnsPolicy: "ClusterFirst"
  imagePullSecrets:
  - name: "registry-credentials"
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 600
  volumes: ~
