---
# The acceptance-tests-brain role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - acceptance-tests-brain: This job will run the testbrain CLI, running all
#   acceptance test scripts in src/testbrain/test-scripts
apiVersion: "v1"
kind: "Pod"
metadata:
  name: "acceptance-tests-brain"
  labels:
    skiff-role-name: "acceptance-tests-brain"
spec:
  containers:
  - env:
    - name: "CLUSTER_ADMIN_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "cluster-admin-password"
          name: "secrets"
    - name: "DOMAIN"
      value: "cf-dev.io"
    - name: "INTERNAL_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-cert"
          name: "secrets"
    - name: "INTERNAL_CA_KEY"
      valueFrom:
        secretKeyRef:
          key: "internal-ca-key"
          name: "secrets"
    - name: "KUBERNETES_NAMESPACE"
      valueFrom:
        fieldRef:
          fieldPath: "metadata.namespace"
    - name: "MONIT_PASSWORD"
      valueFrom:
        secretKeyRef:
          key: "monit-password"
          name: "secrets"
    - name: "SCF_LOG_PROTOCOL"
      value: "tcp"
    - name: "TCP_DOMAIN"
      value: "tcp.cf-dev.io"
    - name: "UAA_CA_CERT"
      valueFrom:
        secretKeyRef:
          key: "uaa-ca-cert"
          name: "secrets"
    image: "splatform/scf-acceptance-tests-brain:7d9a4d8cb72e8222ea63285714283762ad8ed1a8"
    lifecycle:
      preStop:
        exec:
          command:
          - "/opt/fissile/pre-stop.sh"
    livenessProbe: ~
    name: "acceptance-tests-brain"
    ports: ~
    readinessProbe: ~
    resources:
      requests:
        memory: "144Mi"
        cpu: "2000m"
      limits: {}
    securityContext: ~
    volumeMounts: ~
  dnsPolicy: "ClusterFirst"
  imagePullSecrets:
  - name: "registry-credentials"
  restartPolicy: "Never"
  terminationGracePeriodSeconds: 600
  volumes: ~
