---
# The post-deployment-setup role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - uaa-create-user: Create the initial user in UAA
#
# - configure-scf: Uses the cf CLI to configure SCF once it's online (things
#   like proxy settings, service brokers, etc.)
apiVersion: "batch/v1"
kind: "Job"
metadata:
  name: "post-deployment-setup"
spec:
  template:
    metadata:
      name: "post-deployment-setup"
      labels:
        skiff-role-name: "post-deployment-setup"
    spec:
      containers:
      - env:
        - name: "CLUSTER_ADMIN_AUTHORITIES"
          value: "scim.write,scim.read,openid,cloud_controller.admin,clients.read,clients.write,doppler.firehose,routing.router_groups.read,routing.router_groups.write"
        - name: "CLUSTER_ADMIN_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "cluster-admin-password"
              name: "secrets"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "PERSI_NFS_BROKER_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "persi-nfs-broker-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_ADMIN_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-admin-client-secret"
              name: "secrets"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CC_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-cc-client-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_CC_ROUTING_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cc-routing-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_CC_SERVICE_DASHBOARDS_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cc-service-dashboards-client-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_CC_SERVICE_KEY_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cc-service-key-client-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_CF_USB_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cf-usb-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_CLOUD_CONTROLLER_USERNAME_LOOKUP_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cloud-controller-username-lookup-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_DIEGO_SSH_PROXY_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-diego-ssh-proxy-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_DOPPLER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-doppler-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_GOROUTER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-gorouter-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_LOGIN_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-login-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_SCF_AUTO_CONFIG_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-scf-auto-config-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_TCP_EMITTER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-tcp-emitter-secret"
              name: "secrets"
        - name: "UAA_CLIENTS_TCP_ROUTER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-tcp-router-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        image: "splatform/scf-post-deployment-setup:7e1f09fc616bf4fd2761766dddbb5621bbec532b"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "post-deployment-setup"
        ports: ~
        readinessProbe: ~
        resources:
          requests:
            memory: "256Mi"
            cpu: "1000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "OnFailure"
      terminationGracePeriodSeconds: 600
      volumes: ~
