---
# The uaa role contains the following jobs:
#
# - global-uaa-properties: Dummy BOSH job used to host global parameters that
#   are required to configure SCF / fissile
#
# - uaa: The UAA is the identity management service for Cloud Foundry. It's
#   primary role is as an OAuth2 provider, issuing tokens for client
#   applications to use when they act on behalf of Cloud Foundry users. It can
#   also authenticate users with their Cloud Foundry credentials, and can act as
#   an SSO service using those credentials (or others). It has endpoints for
#   managing user accounts and for registering OAuth2 clients, as well as
#   various other management functions.
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "uaa"
  labels:
    skiff-role-name: "uaa"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "uaa"
  template:
    metadata:
      name: "uaa"
      labels:
        skiff-role-name: "uaa"
    spec:
      containers:
      - env:
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "JWT_SIGNING_CERT"
          valueFrom:
            secretKeyRef:
              key: "jwt-signing-cert"
              name: "secrets"
        - name: "JWT_SIGNING_KEY"
          valueFrom:
            secretKeyRef:
              key: "jwt-signing-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SAML_SERVICEPROVIDER_CERT"
          valueFrom:
            secretKeyRef:
              key: "saml-serviceprovider-cert"
              name: "secrets"
        - name: "SAML_SERVICEPROVIDER_KEY"
          valueFrom:
            secretKeyRef:
              key: "saml-serviceprovider-key"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAADB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "uaadb-password"
              name: "secrets"
        - name: "UAA_ADMIN_CLIENT_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-admin-client-secret"
              name: "secrets"
        - name: "UAA_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-server-cert"
              name: "secrets"
        - name: "UAA_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "uaa-server-key"
              name: "secrets"
        image: "splatform/uaa-uaa:eb1e0d9acbbbea452cdf7380125587eb4e8dabd6"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "uaa"
        ports:
        - containerPort: 8080
          name: "uaa"
          protocol: "TCP"
        - containerPort: 8443
          name: "uaa-ssl"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 0
          httpGet:
            httpHeaders:
            - name: "Host"
              value: "uaa"
            - name: "Accept"
              value: "application/json"
            path: "/info"
            port: 8443
            scheme: "HTTPS"
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          requests:
            memory: "2205Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "uaa"
  spec:
    ports:
    - name: "uaa"
      port: 8080
      protocol: "TCP"
      targetPort: "uaa"
    - name: "uaa-ssl"
      port: 2793
      protocol: "TCP"
      targetPort: "uaa-ssl"
    selector:
      skiff-role-name: "uaa"
    type: "ClusterIP"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "uaa-public"
  spec:
    externalIPs: "[ 192.168.77.77 ]"
    ports:
    - name: "uaa-ssl"
      port: 2793
      protocol: "TCP"
      targetPort: "uaa-ssl"
    selector:
      skiff-role-name: "uaa"
    type: "ClusterIP"
kind: "List"
