---
# The blobstore role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - route_registrar: Used for registering routes
#
# Also: blobstore, metron_agent
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "blobstore"
  labels:
    skiff-role-name: "blobstore"
spec:
  replicas: 1
  serviceName: "blobstore-set"
  template:
    metadata:
      name: "blobstore"
      labels:
        skiff-role-name: "blobstore"
    spec:
      containers:
      - env:
        - name: "BLOBSTORE_ACCESS_RULES"
          value: "allow 10.0.0.0/8; allow 172.16.0.0/12; allow 192.168.0.0/16;"
        - name: "BLOBSTORE_MAX_UPLOAD_SIZE"
          value: "5000"
        - name: "BLOBSTORE_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "blobstore-password"
              name: "secrets"
        - name: "BLOBSTORE_SECURE_LINK"
          valueFrom:
            secretKeyRef:
              key: "blobstore-secure-link"
              name: "secrets"
        - name: "BLOBSTORE_TLS_CERT"
          valueFrom:
            secretKeyRef:
              key: "blobstore-tls-cert"
              name: "secrets"
        - name: "BLOBSTORE_TLS_KEY"
          valueFrom:
            secretKeyRef:
              key: "blobstore-tls-key"
              name: "secrets"
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        image: "splatform/scf-blobstore:de04b58c0fabf33320a3b0a24ccb9f2dde19412c"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "blobstore"
        ports:
        - containerPort: 8080
          name: "blobstore-ext"
          protocol: "TCP"
        - containerPort: 4443
          name: "blobstore"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 8080
        resources:
          requests:
            memory: "420Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts:
        - mountPath: "/var/vcap/store"
          name: "blobstore-data"
          readOnly: false
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
  volumeClaimTemplates:
  - metadata:
      name: "blobstore-data"
      annotations:
        volume.beta.kubernetes.io/storage-class: "persistent"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "50G"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "blobstore-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "blobstore-ext"
      port: 8080
      protocol: "TCP"
      targetPort: 0
    - name: "blobstore"
      port: 4443
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "blobstore"
    type: "ClusterIP"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "blobstore"
  spec:
    ports:
    - name: "blobstore-ext"
      port: 8080
      protocol: "TCP"
      targetPort: "blobstore-ext"
    - name: "blobstore"
      port: 4443
      protocol: "TCP"
      targetPort: "blobstore"
    selector:
      skiff-role-name: "blobstore"
    type: "ClusterIP"
kind: "List"
