---
# The cf-usb role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - route_registrar: Used for registering routes
#
# Also: cf-usb
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "cf-usb"
  labels:
    skiff-role-name: "cf-usb"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "cf-usb"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "cf-usb"
      name: "cf-usb"
    spec:
      containers:
      - env:
        - name: "CF_USB_BROKER_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-cert"
              name: "secrets"
        - name: "CF_USB_BROKER_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-broker-server-key"
              name: "secrets"
        - name: "CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "cf-usb-password"
              name: "secrets"
        - name: "DOMAIN"
          value: "cf-dev.io"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_CF_USB_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-cf-usb-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_CF_USB_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-cf-usb-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        image: "splatform/scf-cf-usb:df57dc33bf89f65e5f7264f8432ad97c905137d9"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "cf-usb"
        ports:
        - containerPort: 24054
          name: "usb"
          protocol: "TCP"
        - containerPort: 24053
          name: "usb2"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 24054
        resources:
          requests:
            memory: "117Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "cf-usb"
  spec:
    ports:
    - name: "usb"
      port: 24054
      protocol: "TCP"
      targetPort: "usb"
    - name: "usb2"
      port: 24053
      protocol: "TCP"
      targetPort: "usb2"
    selector:
      skiff-role-name: "cf-usb"
    type: "ClusterIP"
kind: "List"
