---
# The diego-cell role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - wait-for-uaa: Wait for UAA to be ready before starting any jobs
#
# - patch-properties: Dummy BOSH job used to host parameters that are used in
#   SCF patches for upstream bugs
#
# Also: rep, cfdot, route_emitter, garden, cflinuxfs2-rootfs-setup,
# opensuse42-rootfs-setup, cf-sle12-setup, metron_agent, nfsv3driver
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "diego-cell"
  labels:
    skiff-role-name: "diego-cell"
spec:
  replicas: 1
  serviceName: "diego-cell-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "diego-cell"
      name: "diego-cell"
    spec:
      containers:
      - env:
        - name: "BBS_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt"
              name: "secrets"
        - name: "BBS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-key"
              name: "secrets"
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets"
        - name: "BBS_REP_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-key"
              name: "secrets"
        - name: "DIEGO_CELL_DISK_CAPACITY_MB"
          value: "auto"
        - name: "DIEGO_CELL_MEMORY_CAPACITY_MB"
          value: "auto"
        - name: "DIEGO_CELL_NETWORK_MTU"
          value: "1400"
        - name: "DIEGO_CELL_SUBNET"
          value: "10.38.0.0/16"
        - name: "GARDEN_APPARMOR_PROFILE"
          value: "garden-default"
        - name: "GARDEN_DOCKER_REGISTRY"
          value: "registry-1.docker.io"
        - name: "GARDEN_INSECURE_DOCKER_REGISTRIES"
          value: ""
        - name: "GARDEN_LINUX_DNS_SERVER"
          value: "8.8.8.8"
        - name: "GARDEN_ROOTFS_DRIVER"
          value: "btrfs"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "PERSI_NFS_DRIVER_ALLOWED_IN_MOUNT"
          value: "auto_cache"
        - name: "PERSI_NFS_DRIVER_ALLOWED_IN_SOURCE"
          value: "uid,gid"
        - name: "PERSI_NFS_DRIVER_DEFAULT_IN_MOUNT"
          value: "auto_cache:true"
        - name: "PERSI_NFS_DRIVER_DISABLE"
          value: "false"
        - name: "PERSI_NFS_DRIVER_LDAP_HOST"
          value: ""
        - name: "PERSI_NFS_DRIVER_LDAP_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "persi-nfs-driver-ldap-password"
              name: "secrets"
        - name: "PERSI_NFS_DRIVER_LDAP_PORT"
          value: "389"
        - name: "PERSI_NFS_DRIVER_LDAP_PROTOCOL"
          value: "tcp"
        - name: "PERSI_NFS_DRIVER_LDAP_USER"
          value: ""
        - name: "PERSI_NFS_DRIVER_LDAP_USER_FQDN"
          value: ""
        - name: "REP_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "rep-server-cert"
              name: "secrets"
        - name: "REP_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "rep-server-key"
              name: "secrets"
        - name: "ROOTFS_TRUSTED_CERTS"
          value: ""
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "SUSE_STACK"
          value: "opensuse42"
        - name: "SUSE_STACK_DIRNAME"
          value: "opensuse42"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_TCP_EMITTER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-tcp-emitter-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        image: "splatform/scf-diego-cell:5e7554f839ed156a9955a4049af4bc20bd79999b"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-cell"
        ports:
        - containerPort: 1801
          name: "rep-server"
          protocol: "TCP"
        - containerPort: 7589
          name: "nfs-driver"
          protocol: "TCP"
        - containerPort: 7590
          name: "nfs-admin"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 1801
        resources:
          requests:
            memory: "4677Mi"
            cpu: "4000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/var/vcap/data/grootfs"
          name: "grootfs-data"
          readOnly: false
        - mountPath: "/sys/fs/cgroup"
          name: "host-cgroup"
          readOnly: false
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes:
      - name: "host-cgroup"
        hostPath:
          path: "/sys/fs/cgroup"
  volumeClaimTemplates:
  - metadata:
      name: "grootfs-data"
      annotations:
        volume.beta.kubernetes.io/storage-class: "persistent"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "50G"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-cell-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "rep-server"
      port: 1801
      protocol: "TCP"
      targetPort: 0
    - name: "nfs-driver"
      port: 7589
      protocol: "TCP"
      targetPort: 0
    - name: "nfs-admin"
      port: 7590
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "diego-cell"
    type: "ClusterIP"
kind: "List"
