---
# The diego-api role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - patch-properties: Dummy BOSH job used to host parameters that are used in
#   SCF patches for upstream bugs
#
# Also: bbs, cfdot, metron_agent
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "diego-api"
  labels:
    skiff-role-name: "diego-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "diego-api"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "diego-api"
      name: "diego-api"
    spec:
      containers:
      - env:
        - name: "BBS_ACTIVE_KEY_PASSPHRASE"
          valueFrom:
            secretKeyRef:
              key: "bbs-active-key-passphrase"
              name: "secrets"
        - name: "BBS_AUCTIONEER_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-cert"
              name: "secrets"
        - name: "BBS_AUCTIONEER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-auctioneer-key"
              name: "secrets"
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets"
        - name: "BBS_REP_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-key"
              name: "secrets"
        - name: "BBS_SERVER_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-crt"
              name: "secrets"
        - name: "BBS_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-server-key"
              name: "secrets"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_DIEGO_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-diego-api:32688a69a58f204418af742c1c707c876e8a1683"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-api"
        ports:
        - containerPort: 8889
          name: "cell-bbs-api"
          protocol: "TCP"
        - containerPort: 17017
          name: "cell-bbs-dbg"
          protocol: "TCP"
        readinessProbe:
          exec:
            command:
            - "/var/vcap/jobs/global-properties/bin/readiness/diego-api"
          failureThreshold: 0
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          requests:
            memory: "138Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-api"
  spec:
    ports:
    - name: "cell-bbs-api"
      port: 8889
      protocol: "TCP"
      targetPort: "cell-bbs-api"
    - name: "cell-bbs-dbg"
      port: 17017
      protocol: "TCP"
      targetPort: "cell-bbs-dbg"
    selector:
      skiff-role-name: "diego-api"
    type: "ClusterIP"
kind: "List"
