---
# The diego-brain role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - patch-properties: Dummy BOSH job used to host parameters that are used in
#   SCF patches for upstream bugs
#
# Also: auctioneer, cfdot, metron_agent
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "diego-brain"
  labels:
    skiff-role-name: "diego-brain"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "diego-brain"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "diego-brain"
      name: "diego-brain"
    spec:
      containers:
      - env:
        - name: "AUCTIONEER_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "auctioneer-rep-cert"
              name: "secrets"
        - name: "AUCTIONEER_REP_KEY"
          valueFrom:
            secretKeyRef:
              key: "auctioneer-rep-key"
              name: "secrets"
        - name: "AUCTIONEER_SERVER_CERT"
          valueFrom:
            secretKeyRef:
              key: "auctioneer-server-cert"
              name: "secrets"
        - name: "AUCTIONEER_SERVER_KEY"
          valueFrom:
            secretKeyRef:
              key: "auctioneer-server-key"
              name: "secrets"
        - name: "BBS_CLIENT_CRT"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-crt"
              name: "secrets"
        - name: "BBS_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-client-key"
              name: "secrets"
        - name: "BBS_REP_CERT"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-cert"
              name: "secrets"
        - name: "BBS_REP_KEY"
          valueFrom:
            secretKeyRef:
              key: "bbs-rep-key"
              name: "secrets"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-diego-brain:a0757e850bbc7ea5a565250bd2767f9eac647d1d"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-brain"
        ports:
        - containerPort: 9016
          name: "diego-auction"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 9016
        resources:
          requests:
            memory: "99Mi"
            cpu: "4000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-brain"
  spec:
    ports:
    - name: "diego-auction"
      port: 9016
      protocol: "TCP"
      targetPort: "diego-auction"
    selector:
      skiff-role-name: "diego-brain"
    type: "ClusterIP"
kind: "List"
