---
# The diego-locket role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: locket, metron_agent
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "diego-locket"
  labels:
    skiff-role-name: "diego-locket"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "diego-locket"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "diego-locket"
      name: "diego-locket"
    spec:
      containers:
      - env:
        - name: "DIEGO_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "diego-client-cert"
              name: "secrets"
        - name: "DIEGO_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "diego-client-key"
              name: "secrets"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "LOGGREGATOR_CLIENT_CERT"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-cert"
              name: "secrets"
        - name: "LOGGREGATOR_CLIENT_KEY"
          valueFrom:
            secretKeyRef:
              key: "loggregator-client-key"
              name: "secrets"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_DIEGO_LOCKET_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-diego-locket-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-diego-locket:c5b5c2cde81a44de84af5a52e121d68662afee44"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "diego-locket"
        ports:
        - containerPort: 8891
          name: "locket"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 8891
        resources:
          requests:
            memory: "90Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "diego-locket"
  spec:
    ports:
    - name: "locket"
      port: 8891
      protocol: "TCP"
      targetPort: "locket"
    selector:
      skiff-role-name: "diego-locket"
    type: "ClusterIP"
kind: "List"
