---
# The doppler role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: doppler, metron_agent
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "doppler"
  labels:
    skiff-role-name: "doppler"
spec:
  replicas: 1
  serviceName: "doppler-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "doppler"
      name: "doppler"
    spec:
      containers:
      - env:
        - name: "DOPPLER_CERT"
          valueFrom:
            secretKeyRef:
              key: "doppler-cert"
              name: "secrets"
        - name: "DOPPLER_KEY"
          valueFrom:
            secretKeyRef:
              key: "doppler-key"
              name: "secrets"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        image: "splatform/scf-doppler:07462721f39e4ac4ee1267a2b76842ba629d4651"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "doppler"
        ports:
        - containerPort: 3457
          name: "dropsonde-udp"
          protocol: "UDP"
        - containerPort: 3458
          name: "dropsonde-tcp"
          protocol: "TCP"
        - containerPort: 3459
          name: "doppler-tls"
          protocol: "TCP"
        - containerPort: 8081
          name: "doppler-ws"
          protocol: "TCP"
        - containerPort: 8082
          name: "doppler-grpc"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 0
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          tcpSocket:
            port: 8082
          timeoutSeconds: 0
        resources:
          requests:
            memory: "390Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "doppler-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "dropsonde-udp"
      port: 3457
      protocol: "UDP"
      targetPort: 0
    - name: "dropsonde-tcp"
      port: 3458
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-tls"
      port: 3459
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-ws"
      port: 8081
      protocol: "TCP"
      targetPort: 0
    - name: "doppler-grpc"
      port: 8082
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "doppler"
    type: "ClusterIP"
kind: "List"
