---
# The nfs-broker role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# Also: metron_agent, nfsbroker
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "nfs-broker"
  labels:
    skiff-role-name: "nfs-broker"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "nfs-broker"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "nfs-broker"
      name: "nfs-broker"
    spec:
      containers:
      - env:
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "MYSQL_PERSI_NFS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "mysql-persi-nfs-password"
              name: "secrets"
        - name: "PERSI_NFS_ALLOWED_OPTIONS"
          value: "uid,gid,auto_cache,username,password"
        - name: "PERSI_NFS_BROKER_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "persi-nfs-broker-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        image: "splatform/scf-nfs-broker:2b2375a899c28fadea09c3c64aff9d507ccbf16b"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "nfs-broker"
        ports:
        - containerPort: 8999
          name: "nfsbroker"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 8999
        resources:
          requests:
            memory: "63Mi"
            cpu: "2000m"
          limits: {}
        securityContext:
          privileged: true
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "nfs-broker"
  spec:
    ports:
    - name: "nfsbroker"
      port: 8999
      protocol: "TCP"
      targetPort: "nfsbroker"
    selector:
      skiff-role-name: "nfs-broker"
    type: "ClusterIP"
kind: "List"
