---
# The postgres role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - postgres: The Postgres server provides a single instance Postgres database
#   that can be used with the Cloud Controller or the UAA. It does not provide
#   highly-available configuration.
apiVersion: "apps/v1beta1"
kind: "StatefulSet"
metadata:
  name: "postgres"
  labels:
    skiff-role-name: "postgres"
spec:
  replicas: 1
  serviceName: "postgres-set"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "postgres"
      name: "postgres"
    spec:
      containers:
      - env:
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "POSTGRES_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "postgres-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        image: "splatform/scf-postgres:4657f2da11483737b8e178eee39c82fe000825bf"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "postgres"
        ports:
        - containerPort: 5524
          name: "postgres"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 5524
        resources:
          requests:
            memory: "3072Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts:
        - mountPath: "/var/vcap/store"
          name: "postgres-data"
          readOnly: false
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
  volumeClaimTemplates:
  - metadata:
      name: "postgres-data"
      annotations:
        volume.beta.kubernetes.io/storage-class: "persistent"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "20G"
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "postgres-set"
  spec:
    clusterIP: "None"
    ports:
    - name: "postgres"
      port: 5524
      protocol: "TCP"
      targetPort: 0
    selector:
      skiff-role-name: "postgres"
    type: "ClusterIP"
kind: "List"
