---
# The router role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# - authorize-internal-ca: Install both internal and UAA CA certificates
#
# - gorouter: Gorouter maintains a dynamic routing table based on updates
#   received from NATS and (when enabled) the Routing API. This routing table
#   maps URLs to backends. The router finds the URL in the routing table that
#   most closely matches the host header of the request and load balances across
#   the associated backends.
#
# Also: metron_agent
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "router"
  labels:
    skiff-role-name: "router"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "router"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "router"
      name: "router"
    spec:
      containers:
      - env:
        - name: "DNS_HEALTH_CHECK_HOST"
          value: "127.0.0.1"
        - name: "FORCE_FORWARDED_PROTO_AS_HTTPS"
          value: "false"
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "KUBE_SIZING_NATS_COUNT"
          value: "1"
        - name: "LOG_LEVEL"
          value: "info"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "NATS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "nats-password"
              name: "secrets"
        - name: "ROUTER_BALANCING_ALGORITHM"
          value: "round-robin"
        - name: "ROUTER_FORWARDED_CLIENT_CERT"
          value: "always_forward"
        - name: "ROUTER_SERVICES_SECRET"
          valueFrom:
            secretKeyRef:
              key: "router-services-secret"
              name: "secrets"
        - name: "ROUTER_SSL_CERT"
          valueFrom:
            secretKeyRef:
              key: "router-ssl-cert"
              name: "secrets"
        - name: "ROUTER_SSL_KEY"
          valueFrom:
            secretKeyRef:
              key: "router-ssl-key"
              name: "secrets"
        - name: "ROUTER_STATUS_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "router-status-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "UAA_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "uaa-ca-cert"
              name: "secrets"
        - name: "UAA_CLIENTS_GOROUTER_SECRET"
          valueFrom:
            secretKeyRef:
              key: "uaa-clients-gorouter-secret"
              name: "secrets"
        - name: "UAA_HOST"
          value: "uaa.cf-dev.io"
        - name: "UAA_PORT"
          value: "2793"
        image: "splatform/scf-router:0a79f844cec57faccf57477085ccd922d0fce955"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "router"
        ports:
        - containerPort: 80
          name: "router"
          protocol: "TCP"
        - containerPort: 443
          name: "router2"
          protocol: "TCP"
        - containerPort: 443
          name: "router3"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 0
          httpGet:
            path: "/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          requests:
            memory: "135Mi"
            cpu: "4000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "router"
  spec:
    ports:
    - name: "router"
      port: 80
      protocol: "TCP"
      targetPort: "router"
    - name: "router2"
      port: 443
      protocol: "TCP"
      targetPort: "router2"
    - name: "router3"
      port: 4443
      protocol: "TCP"
      targetPort: "router3"
    selector:
      skiff-role-name: "router"
    type: "ClusterIP"
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "router-public"
  spec:
    externalIPs: "[ 192.168.77.77 ]"
    ports:
    - name: "router"
      port: 80
      protocol: "TCP"
      targetPort: "router"
    - name: "router2"
      port: 443
      protocol: "TCP"
      targetPort: "router2"
    - name: "router3"
      port: 4443
      protocol: "TCP"
      targetPort: "router3"
    selector:
      skiff-role-name: "router"
    type: "ClusterIP"
kind: "List"
