---
# The syslog-adapter role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: adapter, metron_agent
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "syslog-adapter"
  labels:
    skiff-role-name: "syslog-adapter"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "syslog-adapter"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "syslog-adapter"
      name: "syslog-adapter"
    spec:
      containers:
      - env:
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "SYSLOG_ADAPT_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-adapt-cert"
              name: "secrets"
        - name: "SYSLOG_ADAPT_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-adapt-key"
              name: "secrets"
        image: "splatform/scf-syslog-adapter:3a0e3be07ce5552bf1a7aced03acdeb40b1c4729"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "syslog-adapter"
        ports:
        - containerPort: 4443
          name: "adapter"
          protocol: "TCP"
        - containerPort: 8080
          name: "adapter-health"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 0
          httpGet:
            path: "/health"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 0
          successThreshold: 0
          timeoutSeconds: 0
        resources:
          requests:
            memory: "78Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "syslog-adapter"
  spec:
    ports:
    - name: "adapter"
      port: 4443
      protocol: "TCP"
      targetPort: "adapter"
    - name: "adapter-health"
      port: 8080
      protocol: "TCP"
      targetPort: "adapter-health"
    selector:
      skiff-role-name: "syslog-adapter"
    type: "ClusterIP"
kind: "List"
