---
# The syslog-rlp role contains the following jobs:
#
# - global-properties: Dummy BOSH job used to host global parameters that are
#   required to configure SCF
#
# Also: metron_agent, reverse_log_proxy
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "syslog-rlp"
  labels:
    skiff-role-name: "syslog-rlp"
spec:
  replicas: 1
  selector:
    matchLabels:
      skiff-role-name: "syslog-rlp"
  template:
    metadata:
      annotations: {}
      labels:
        skiff-role-name: "syslog-rlp"
      name: "syslog-rlp"
    spec:
      containers:
      - env:
        - name: "INTERNAL_CA_CERT"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-cert"
              name: "secrets"
        - name: "INTERNAL_CA_KEY"
          valueFrom:
            secretKeyRef:
              key: "internal-ca-key"
              name: "secrets"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "KUBE_AZ"
          value: "z1"
        - name: "METRON_CERT"
          valueFrom:
            secretKeyRef:
              key: "metron-cert"
              name: "secrets"
        - name: "METRON_KEY"
          valueFrom:
            secretKeyRef:
              key: "metron-key"
              name: "secrets"
        - name: "MONIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "monit-password"
              name: "secrets"
        - name: "SCF_LOG_PROTOCOL"
          value: "tcp"
        - name: "SYSLOG_RLP_CERT"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-cert"
              name: "secrets"
        - name: "SYSLOG_RLP_KEY"
          valueFrom:
            secretKeyRef:
              key: "syslog-rlp-key"
              name: "secrets"
        image: "splatform/scf-syslog-rlp:04110d763ca1003c8021346c0f071851dd11651b"
        lifecycle:
          preStop:
            exec:
              command:
              - "/opt/fissile/pre-stop.sh"
        livenessProbe: ~
        name: "syslog-rlp"
        ports:
        - containerPort: 8082
          name: "rlp"
          protocol: "TCP"
        readinessProbe:
          tcpSocket:
            port: 8082
        resources:
          requests:
            memory: "93Mi"
            cpu: "2000m"
          limits: {}
        securityContext: ~
        volumeMounts: ~
      dnsPolicy: "ClusterFirst"
      imagePullSecrets:
      - name: "registry-credentials"
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 600
      volumes: ~
---
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    name: "syslog-rlp"
  spec:
    ports:
    - name: "rlp"
      port: 8082
      protocol: "TCP"
      targetPort: "rlp"
    selector:
      skiff-role-name: "syslog-rlp"
    type: "ClusterIP"
kind: "List"
